import { z } from "zod"

export const streamingIndicatorSchema = z.object({
  message: z
    .string()
    .optional()
    .describe("Optional message to display next to the indicator (e.g., 'Analyzing data...', 'Generating response...')"),
  variant: z
    .enum(["dots", "pulse", "spinner", "typing", "progress"])
    .default("dots")
    .describe(
      "Visual variant of the indicator:\n" +
      "- 'dots': Three bouncing dots (default, good for general loading)\n" +
      "- 'pulse': Pulsing circles (good for processing states)\n" +
      "- 'spinner': Rotating spinner (traditional loading indicator)\n" +
      "- 'typing': Typing indicator with 'AI is typing...' text (perfect for chat/LLM responses)\n" +
      "- 'progress': Step-by-step progress indicator with completion checkmarks (requires 'steps' prop)"
    ),
  steps: z
    .array(
      z.object({
        label: z
          .string()
          .describe("Step description (e.g., 'Analyzing...', 'Generating...', 'Formatting...')"),
        status: z
          .enum(["pending", "active", "completed"])
          .describe(
            "Step status:\n" +
            "- 'pending': Not yet started (gray circle)\n" +
            "- 'active': Currently processing (spinning indicator)\n" +
            "- 'completed': Finished (green checkmark)"
          ),
      })
    )
    .optional()
    .describe("Array of steps for 'progress' variant. Shows multi-step process with visual status indicators."),
  tokenCount: z
    .number()
    .optional()
    .describe("Number of tokens processed/generated by the LLM (for display in token counter)"),
  showTokenCounter: z
    .boolean()
    .default(false)
    .describe("Whether to show the token counter. Only displayed if 'tokenCount' is provided."),
  className: z
    .string()
    .optional()
    .describe("Additional CSS classes to apply to the indicator container"),
})

export type StreamingIndicatorProps = z.infer<typeof streamingIndicatorSchema>
